---
  - name: "Установка Nginx на ноды web1 и web2"
    import_playbook: 1_nginx_install.yaml
  
  - name: "Устанавливаем Prometheus"
    import_playbook: 4_prometheus_install.yaml

  - name: "Устанавливаем Grafana"
    import_playbook: 5_grafana_install.yaml

  - name: "Устанавливаем elastic"
    import_playbook: 3_elastic_install.yaml

  - name: "Устанавливаем Kibana"
    import_playbook: 2_kibana_install.yaml

  - name: "Устанавливаем filebeat"
    import_playbook: 6_filebeat_install.yaml
