- hosts: web
  become: yes
  gather_facts: true
  tasks:

  - name: "Создаем директорию filebeat"
    file:
      path: "/tmp/filebeat"
      state: directory
      
  - name: "Загружаем filebeat"
    copy:
      src: "/home/alifanov/source/filebeat-8.9.0-amd64.deb"
      dest: /tmp/filebeat

  - name: "Устанавливаем filebeat"
    apt:
      deb: "/tmp/filebeat/filebeat-8.9.0-amd64.deb"

  - name: "Копируем конфигурационнй файл:"
    copy:
      src: filebeat.yml
      dest: /etc/filebeat/filebeat.yml

  - name: "Проверяем работоспособность сервиса:"
    systemd:
      state: started
      name: filebeat
