- hosts: grafana
  become: yes
  gather_facts: true
  roles:
  - node-exporter
  - grafana
  vars:
    grafana_version: latest
    
    grafana_security:
      admin_user: admin
      admin_password: admin

    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: "http://192.168.4.50:9090"
        basicAuth: false
    
    grafana_dashboards:
      - dashboard_id: 1860
        revision_id: 33
        datasource: prometheus

      - dashboard_id: 15947
        revision_id: 1
        datasource: prometheus

