---
- hosts: prometheus
  hosts: prometheus
  roles:
  - node_exporter
  - prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - "192.168.1.10:9100" #web1
        - "192.168.2.10:9100" #web2
        - "192.168.3.30:9100" #prometheus
        - "192.168.3.40:9100" #elastic
        - "192.168.4.50:9100" #grafana
        - "192.168.4.60:9100" #kibana


      nginx:
      - targets:
        - "192.168.1.10:4040"
        - "192.168.2.10:4040"

    prometheus_scrape_configs:
      - job_name: "node"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml"
      - job_name: "nginx"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/nginx.yml"
