---
- hosts: prometheus
  roles:
  - node-exporter
  - prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - "{{ groups['web'][0] }}:9100" #web1
        - "{{ groups['web'][1] }}:9100" #web2
        - "{{ groups['prometheus'][0] }}:9100" #prometheus
        - "{{ groups['elastic'][0] }}:9100" #elastic
        - "{{ groups['grafana'][0] }}:9100" #grafana
        - "{{ groups['kibana'][0] }}:9100" #kibana


      nginx:
      - targets:
        - "{{ groups['web'][0] }}:4040"
        - "{{ groups['web'][1] }}:4040"

    prometheus_scrape_configs:
      - job_name: "node"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml"
      - job_name: "nginx"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/nginx.yml"
