- hosts: web
  become: yes
  tasks:
  - name: "Устанавливаем nginx:"
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: "Создаем директорию www"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'

  - name: "Удаляем дефолтный шаблон сайта:"
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: "Копируем конфигурационный файл:"
    copy:
      src: ./nginx/nginx.conf 
      dest: /etc/nginx/
    notify: restart nginx

  - name: "Копируем конфигурационный файл сайта:"
    template:
      src: ./nginx/templates/site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: Изменяем
    template:
      src: templates/content
      dest: /var/www/html/index.nginx-debian.html
        
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
