---
- name: "Remove conflicting grafana packages"
  ansible.builtin.package:
    name: grafana-data
    state: absent

- name: "Install dependencies"
  ansible.builtin.package:
    name: "{{ _grafana_dependencies }}"
    state: present
    update_cache: true
  when: "(_grafana_dependencies | default())"

- name: "install Grafana"
  apt:
    deb: https://dl.grafana.com/enterprise/release/grafana-enterprise_10.2.1_amd64.deb
  notify: restart_grafana
